### ISSUE TITLE
Unable to create a module

### ISSUE THREAD

**Issue by Eromera** [AXeL-dev/dolibase#1]
Hi! 
Thanks a lot for your work. The module seems super useful but I am unable to use it. I followed the youtube tutorial to install dolibase and create a new module, but as soon as I try to create a new module with the module builder and fill the required fields it always says: "Module folder /custom/name already exists.", no matter what the name is. Also if I try to press anything on the left panel I get the message: 

`Warning: dir(): open_basedir restriction in effect. File(/custom) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\dolibase\builder\lib\functions.php on line 280

Warning: dir(/custom): failed to open dir: Operation not permitted in C:\dolibarr\www\dolibarr\htdocs\dolibase\builder\lib\functions.php on line 280

Fatal error: Call to a member function read() on a non-object in C:\dolibarr\www\dolibarr\htdocs\dolibase\builder\lib\functions.php on line 283`

Is there something missing in the initialization? Thanks!

**Comment by Eromera** [comment]
Hi again, I believe the problem is related to an incompatibility with Windows, I believe all paths in your php code have slashes in the unix-way so folder creation fails. Am I right? If so, do you think it would be easy making all windows compatible?

**Comment by Eromera** [comment]
Effectively the problem is due to compatibility in the slashes, but apparently it's not needed to change all slashes in module.py to make it work, just this function in functions.php and php makes it work for the rest:

`function getDolibarrRootDirectory()
{
	$path = defined(__DIR__) ? __DIR__ : dirname(__FILE__); // should be: .../dolibarr/dolibase/builder/lib
	$parts = explode('\\', $path);
	array_splice($parts, -3); // remove '/dolibase/builder/lib'
	$root_path = implode('\\', $parts);

	return $root_path;
}`

**Comment by AXeL-dev** [comment]
Can you check if it works now?

**Comment by AXeL-dev** [comment]
In fact, the problem was more exactly on this line
https://github.com/AXeL-dev/dolibase/blob/78da77897b023699af9230ec9020c163b8a5dc7b/builder/lib/functions.php#L108

So it should work properly on both windows & linux now.

**Comment by Eromera** [comment]
Thanks, how can I work directly with the github version? Can I just download the github to the dolibarr folder and do git pulls there for this module? Or how do you normally work with it?

**Comment by AXeL-dev** [comment]
Welcome, i already updated the [Dolibase installer](https://www.dolistore.com/en/modules/1060-Dolibase-Installer.html), so you can simply update the module & after that disable + re-enable it (to refresh the dolibase framework files).

Solution 2 (using github version): download dolibase zip file from [here](/AXeL-dev/dolibase/archive/master.zip) then delete your old dolibase folder from your dolibarr root directory (it should be in `/dolibarr/dolibase` or `/dolibarr/htdocs/dolibase`) & finally replace it with the extracted one from the master.zip file.

**Comment by Eromera** [comment]
Thanks! It seems to work now. However I keep getting a warning when I select any "Page" item on the left:
`Warning: Invalid argument supplied for foreach() in C:\dolibarr\www\dolibarr\htdocs\dolibase\builder\lib\functions.php on line 185
`
Is this the expected behaviour?

Additionally, do you have some quick tutorial/video about how to use the left panel (e.g. widgets / page) to create a module? Thanks!
